//! Generate `common_words.txt` from a whisper ggml model's tokenizer vocabulary.
//!
//! Tokens are stored in id order, which follows BPE merge rank (roughly corpus
//! frequency). The list keeps whole-word tokens: a leading space followed only
//! by lowercase ASCII letters (two or more letters, plus "a" and "i"), in id
//! order, deduplicated, up to the requested count.
//!
//! ```text
//! cargo run --example common_words -- ~/.glassrip/models/ggml-large-v3-turbo.bin 5000 > common_words.txt
//! ```

use std::error::Error;
use std::io::{BufReader, Read};

fn read_u32(r: &mut impl Read) -> std::io::Result<u32> {
    let mut b = [0u8; 4];
    r.read_exact(&mut b)?;
    Ok(u32::from_le_bytes(b))
}

fn main() -> Result<(), Box<dyn Error>> {
    let mut args = std::env::args().skip(1);
    let path = args.next().ok_or("usage: common_words MODEL.bin [COUNT]")?;
    let count: usize = args.next().map_or(Ok(5000), |c| c.parse())?;
    let mut r = BufReader::new(std::fs::File::open(&path)?);
    if read_u32(&mut r)? != 0x6767_6d6c {
        return Err("not a ggml whisper model (bad magic)".into());
    }
    for _ in 0..11 {
        read_u32(&mut r)?; // hparams
    }
    let n_mel = read_u32(&mut r)? as u64;
    let n_fft = read_u32(&mut r)? as u64;
    std::io::copy(&mut (&mut r).take(n_mel * n_fft * 4), &mut std::io::sink())?;
    let n_vocab = read_u32(&mut r)?;
    let mut seen = std::collections::HashSet::new();
    let mut out = Vec::new();
    for _ in 0..n_vocab {
        let len = read_u32(&mut r)? as usize;
        let mut w = vec![0u8; len];
        r.read_exact(&mut w)?;
        let Some(rest) = w.strip_prefix(b" ") else {
            continue;
        };
        if rest.is_empty() || !rest.iter().all(u8::is_ascii_lowercase) {
            continue;
        }
        if rest.len() < 2 && rest != b"a" && rest != b"i" {
            continue;
        }
        let s = String::from_utf8(rest.to_vec())?;
        if seen.insert(s.clone()) {
            out.push(s);
            if out.len() == count {
                break;
            }
        }
    }
    println!("# Common English words for the vocabulary correction guard.");
    println!(
        "# Generated by `cargo run --example common_words -- ggml-large-v3-turbo.bin {count}`:"
    );
    println!("# whole lowercase word tokens of the whisper tokenizer (MIT) in token id order.");
    for w in out {
        println!("{w}");
    }
    Ok(())
}
