//! Schema evolution: `schema_version`-tagged enums that migrate into the current type.
//!
//! Pattern:
//!
//! 1. Keep every released version of a type as its own struct (`FooV1`, `FooV2`, ...),
//!    each with `#[serde(deny_unknown_fields)]`. Released structs are frozen.
//! 2. Declare the tagged enum with [`versioned_enum!`](crate::versioned_enum). It
//!    derives `Serialize`, `Deserialize`, and `JsonSchema` with
//!    `#[serde(tag = "schema_version")]`, renames each variant to its exact semver
//!    string, and implements [`Versioned`].
//! 3. Implement [`Migrate`] for the enum, converting every variant into the current
//!    struct (usually by chaining one-step upgrades).
//! 4. Read with [`decode_versioned`], which rejects unknown versions with a typed
//!    error before attempting a parse, then migrates.
//!
//! A worked example lives in [`example`].

use serde::de::DeserializeOwned;
use serde_json::Value;

/// Implemented by `schema_version`-tagged enums (generated by
/// [`versioned_enum!`](crate::versioned_enum)).
pub trait Versioned {
    /// Every accepted `schema_version` tag, oldest first.
    const VERSIONS: &'static [&'static str];
    /// The tag of this value.
    fn schema_version(&self) -> &'static str;
}

/// Converts any supported version into the current type.
pub trait Migrate: Sized {
    /// The current (latest) type.
    type Current;
    /// Performs the migration.
    fn migrate(self) -> Result<Self::Current, MigrationError>;
}

/// A value could not be migrated into the current version.
#[derive(Debug, Clone, PartialEq, thiserror::Error)]
#[error("cannot migrate from schema_version {from}: {reason}")]
pub struct MigrationError {
    /// Version being migrated from.
    pub from: String,
    /// Why.
    pub reason: String,
}

/// Error from [`decode_versioned`].
#[derive(Debug, thiserror::Error)]
pub enum VersionedDecodeError {
    /// The value has no string `schema_version` field.
    #[error("missing or non-string `schema_version` field")]
    MissingVersion,
    /// The version tag is not one this build understands.
    #[error("unknown schema_version `{found}` (known: {known:?})")]
    UnknownVersion {
        /// Tag found.
        found: String,
        /// Tags this build accepts.
        known: Vec<String>,
    },
    /// The value did not match its version's type.
    #[error("value does not match its schema_version: {0}")]
    Parse(#[from] serde_json::Error),
    /// Migration failed.
    #[error(transparent)]
    Migration(#[from] MigrationError),
}

/// Decodes a tagged value of any supported version and migrates it to current.
pub fn decode_versioned<V>(value: Value) -> Result<V::Current, VersionedDecodeError>
where
    V: Versioned + Migrate + DeserializeOwned,
{
    let tag = value
        .get("schema_version")
        .and_then(Value::as_str)
        .ok_or(VersionedDecodeError::MissingVersion)?;
    if !V::VERSIONS.contains(&tag) {
        return Err(VersionedDecodeError::UnknownVersion {
            found: tag.to_string(),
            known: V::VERSIONS.iter().map(|s| s.to_string()).collect(),
        });
    }
    let parsed: V = serde_json::from_value(value)?;
    Ok(parsed.migrate()?)
}

/// Declares a `schema_version`-tagged enum over frozen version structs.
///
/// The calling crate must depend on `serde` (with `derive`) and `schemars`, because
/// the generated derives refer to them by name.
///
/// ```
/// use glassrip_core::versioned_enum;
/// # #[derive(Debug, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
/// # #[serde(deny_unknown_fields)]
/// # pub struct WidgetV1 { pub n: u32 }
/// versioned_enum! {
///     /// All versions of a widget.
///     #[derive(Debug)]
///     pub enum WidgetVersions {
///         "1.0.0" => V1(WidgetV1),
///     }
/// }
/// ```
#[macro_export]
macro_rules! versioned_enum {
    (
        $(#[$meta:meta])*
        $vis:vis enum $name:ident {
            $( $ver:literal => $variant:ident($ty:ty) ),+ $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(::serde::Serialize, ::serde::Deserialize, ::schemars::JsonSchema)]
        #[serde(tag = "schema_version")]
        $vis enum $name {
            $(
                #[doc = concat!("schema_version ", $ver)]
                #[serde(rename = $ver)]
                $variant($ty),
            )+
        }

        impl $crate::versioning::Versioned for $name {
            const VERSIONS: &'static [&'static str] = &[$($ver),+];
            fn schema_version(&self) -> &'static str {
                match self {
                    $( Self::$variant(_) => $ver, )+
                }
            }
        }
    };
}

pub mod example {
    //! Worked example: a score record that changed shape between versions.
    //!
    //! - `1.0.0`: `{label, score_pct}` with an integer percentage.
    //! - `2.0.0`: `{label, score, tags}` with a float in [0, 1] and a tag list.

    use super::{Migrate, MigrationError};
    use schemars::JsonSchema;
    use serde::{Deserialize, Serialize};

    /// Version 1 (frozen).
    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
    #[serde(deny_unknown_fields)]
    pub struct ExampleScoreV1 {
        /// Label.
        pub label: String,
        /// Percentage 0 to 100.
        pub score_pct: u8,
    }

    /// Version 2 (current).
    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
    #[serde(deny_unknown_fields)]
    pub struct ExampleScoreV2 {
        /// Label.
        pub label: String,
        /// Score in [0, 1].
        pub score: f64,
        /// Free-form tags.
        pub tags: Vec<String>,
    }

    crate::versioned_enum! {
        /// Every released version of the example score.
        #[derive(Debug, Clone, PartialEq)]
        pub enum ExampleScore {
            "1.0.0" => V1(ExampleScoreV1),
            "2.0.0" => V2(ExampleScoreV2),
        }
    }

    impl ExampleScoreV1 {
        fn upgrade(self) -> Result<ExampleScoreV2, MigrationError> {
            if self.score_pct > 100 {
                return Err(MigrationError {
                    from: "1.0.0".into(),
                    reason: format!("score_pct {} is above 100", self.score_pct),
                });
            }
            Ok(ExampleScoreV2 {
                label: self.label,
                score: f64::from(self.score_pct) / 100.0,
                tags: Vec::new(),
            })
        }
    }

    impl Migrate for ExampleScore {
        type Current = ExampleScoreV2;

        fn migrate(self) -> Result<ExampleScoreV2, MigrationError> {
            match self {
                Self::V1(v1) => v1.upgrade(),
                Self::V2(v2) => Ok(v2),
            }
        }
    }

    impl From<ExampleScoreV2> for ExampleScore {
        fn from(current: ExampleScoreV2) -> Self {
            Self::V2(current)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::example::*;
    use super::*;
    use serde_json::json;

    #[test]
    fn migrates_v1() {
        let v = json!({"schema_version": "1.0.0", "label": "alpha", "score_pct": 42});
        let current = decode_versioned::<ExampleScore>(v).unwrap();
        assert_eq!(
            current,
            ExampleScoreV2 {
                label: "alpha".into(),
                score: 0.42,
                tags: vec![]
            }
        );
    }

    #[test]
    fn reads_current() {
        let v = json!({"schema_version": "2.0.0", "label": "beta", "score": 0.5, "tags": ["t"]});
        let current = decode_versioned::<ExampleScore>(v).unwrap();
        assert_eq!(current.tags, vec!["t".to_string()]);
    }

    #[test]
    fn writes_tag() {
        let value = serde_json::to_value(ExampleScore::from(ExampleScoreV2 {
            label: "gamma".into(),
            score: 1.0,
            tags: vec![],
        }))
        .unwrap();
        assert_eq!(value["schema_version"], json!("2.0.0"));
        assert_eq!(ExampleScore::VERSIONS, &["1.0.0", "2.0.0"]);
    }

    #[test]
    fn unknown_version_rejected() {
        let v = json!({"schema_version": "3.0.0", "label": "x"});
        assert!(matches!(
            decode_versioned::<ExampleScore>(v),
            Err(VersionedDecodeError::UnknownVersion { .. })
        ));
        assert!(matches!(
            decode_versioned::<ExampleScore>(json!({"label": "x"})),
            Err(VersionedDecodeError::MissingVersion)
        ));
    }

    #[test]
    fn unknown_field_in_old_version_rejected() {
        let v = json!({"schema_version": "1.0.0", "label": "x", "score_pct": 1, "tags": []});
        assert!(matches!(
            decode_versioned::<ExampleScore>(v),
            Err(VersionedDecodeError::Parse(_))
        ));
    }

    #[test]
    fn migration_failure_is_typed() {
        let v = json!({"schema_version": "1.0.0", "label": "x", "score_pct": 150});
        assert!(matches!(
            decode_versioned::<ExampleScore>(v),
            Err(VersionedDecodeError::Migration(_))
        ));
    }

    #[test]
    fn schema_generates() {
        let s = schemars::schema_for!(ExampleScore);
        let text = serde_json::to_string(&s).unwrap();
        assert!(text.contains("1.0.0") && text.contains("2.0.0"));
    }
}
